version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: studybites-test
    ports:
      - '5504:5432'
    volumes:
      - studybites-db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile_test
    depends_on:
      - postgres
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/studybites-test
      PORT: 3017
      JWT_SECRET: tvXqYGduhyMw28EzyBxaGrFP8zQsmRG93GZHrmADmHsU9WwB7nbULUsJ98aAqWzM
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studybites-test
    ports:
      - '3018:3017'

volumes:
  studybites-db:
