version: '3.7'

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  db:
    ports:
      - '5503:5432'
    volumes:
      - studybites:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
  s3:
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage:/data
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
  scheduler:
    command: yarn run:dev
    volumes:
      - ./scheduler:/scheduler
      - /scheduler/node_modules
    environment:
      DATABASE_URL: ${POSTGRES_URI}
  api:
    command: yarn run:dev
    ports:
      - '3017:3017'
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      PORT: ${API_PORT}
      DEVELOPMENT_MODE: 1
      DATABASE_URL: ${POSTGRES_URI}

volumes:
  studybites:
