version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  s3:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
  rabbit:
    image: rabbitmq:alpine
  mailer:
    build:
      context: ./mailer
      dockerfile: .docker/Dockerfile.dev
    depends_on:
      - rabbit
  api:
    build:
      context: ./api
      dockerfile: .docker/Dockerfile.dev
    depends_on:
      - db
      - s3
      - rabbit
    environment:
      SB_ADMIN_EMAIL: ${SB_ADMIN_EMAIL}
      SB_ADMIN_PASSWORD: ${SB_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      S3_HOST: s3
      S3_PORT: 9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: storage
      SB_HOST: ${SB_HOST}
      REDIS_PORT: 6379
      SMTP_PORT: 465
