version: '3.7'

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
        - "6379:6379"
    environment:
        - REDIS_REPLICATION_MODE=master
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5503:5432'
    volumes:
      - studybites-db:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  studybites-api:
    build: ./api
    depends_on:
      - postgres
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      SB_ADMIN_EMAIL: ${SB_ADMIN_EMAIL}
      SB_ADMIN_PASSWORD: ${SB_ADMIN_PASSWORD}
      SB_MAIL_USER: ${SB_MAIL_USER}
      SB_MAIL_PASSWORD: ${SB_MAIL_PASSWORD}
      DATABASE_URL: postgres://postgres:@postgres:5432/studybites
      PORT: 3017
      JWT_SECRET: tvXqYGduhyMw28EzyBxaGrFP8zQsmRG93GZHrmADmHsU9WwB7nbULUsJ98aAqWzM
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studybites
      API_LOGLEVEL: info
    ports:
      - '3017:3017'

  studybites-front:
    build: ./front
    volumes:
      - ./front:/front
      - /front/node_modules
    ports:
      - '3018:3018'
    environment:
      PORT: 3018
      API_PORT: 3017

volumes:
  studybites-db:
