version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5503:5432'
    volumes:
      - studybites-db:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  studybites-api:
    build: ./api
    depends_on:
      - postgres
      - s3
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      SB_ADMIN_EMAIL: ${SB_ADMIN_EMAIL}
      SB_ADMIN_PASSWORD: ${SB_ADMIN_PASSWORD}
      DATABASE_URL: postgres://postgres:@postgres:5432/studybites
      PORT: 3017
      JWT_SECRET: tvXqYGduhyMw28EzyBxaGrFP8zQsmRG93GZHrmADmHsU9WwB7nbULUsJ98aAqWzM
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studybites
      API_LOGLEVEL: info
      S3_HOST: s3
      S3_PORT: 9000
      S3_ACCESS_KEY: minio_access_key
      S3_SECRET_KEY: minio_secret_key
      S3_BUCKET: storage
    ports:
      - '3017:3017'

  s3:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data

  studybites-front:
    build: ./front
    volumes:
      - ./front:/front
      - /front/node_modules
    ports:
      - '3018:3018'
    environment:
      PORT: 3018
      API_PORT: 3017

volumes:
  studybites-db:
