#!/bin/bash

# start docker to run tests
docker-compose -p test -f api-integration-test-compose.yaml up -d --build;
# display tests output
docker logs test_api_1 -f;
# write exit code of the api container to the $status
status=$(docker inspect test_api_1 --format='{{.State.ExitCode}}');
# stop docker
docker-compose -p test down -v --remove-orphans;
# check $status
# if tests have failed
if [ $status -ne 0 ]; then
# exit with 1
	exit 1;
else
# exit with 0
	exit 0;
fi
