import { BLOCKS_TYPE } from '@sb-ui/pages/User/LearnPage/BlockElement/types';

export const SELF_STALE_TIME = 60_000; // 60 seconds

export const interactiveTypesBlocks = [
  BLOCKS_TYPE.NEXT,
  BLOCKS_TYPE.QUIZ,
  BLOCKS_TYPE.CLOSED_QUESTION,
  BLOCKS_TYPE.FILL_THE_GAP,
  BLOCKS_TYPE.BRICKS,
  BLOCKS_TYPE.MATCH,
  BLOCKS_TYPE.GRADED_QUESTION,
];
export const staticTypesBlocks = [
  BLOCKS_TYPE.PARAGRAPH,
  BLOCKS_TYPE.EMBED,
  BLOCKS_TYPE.ATTACH,
  BLOCKS_TYPE.CODE,
  BLOCKS_TYPE.EMBED,
  BLOCKS_TYPE.IMAGE,
  BLOCKS_TYPE.LIST,
  BLOCKS_TYPE.HEADER,
  BLOCKS_TYPE.QUOTE,
  BLOCKS_TYPE.DELIMITER,
  BLOCKS_TYPE.TABLE,
  BLOCKS_TYPE.WARNING,
];
