const variables = {
  'primary-color': '#098C8C',
  'text-table-header': 'rgba(0, 0, 0, 0.45)',
  'text-color': 'rgba(0, 0, 0, 0.85)',
  'progress-trail-color': 'white',
  'learn-chunk-background': '#f5f5f5',
  'secondary-text-color': '#595959',
  'placeholder-color': '#bfbfbf',
  'checkbox-disabled': '#8c8c8c',
};

module.exports = variables;

// !!!!!!!!!!!!!!!!!!!
// DEFAULT VARIABLES
// !!!!!!!!!!!!!!!!!!!

// alert-success-border-color: "#b7eb8f"
// alert-success-icon-color: "#52c41a"
// alert-text-color: "rgba(0, 0, 0, 0.85)"
// alert-warning-bg-color: "#fffbe6"
// alert-warning-border-color: "#ffe58f"
// alert-warning-icon-color: "#faad14"
// alert-with-description-icon-size: "24px"
// alert-with-description-no-icon-padding-vertical: "15px"
// alert-with-description-padding: "15px 15px 15px 24px"
// alert-with-description-padding-vertical: "15px"
// anchor-bg: "transparent"
// anchor-border-color: "#f0f0f0"
// anchor-link-left: "16px"
// anchor-link-padding: "7px 0 7px 16px"
// anchor-link-top: "7px"
// animation-duration-base: "0.2s"
// animation-duration-fast: "0.1s"
// animation-duration-slow: "0.3s"
// ant-prefix: "ant"
// avatar-bg: "#ccc"
// avatar-border-radius: "2px"
// avatar-color: "#fff"
// avatar-font-size-base: "18px"
// avatar-font-size-lg: "24px"
// avatar-font-size-sm: "14px"
// avatar-group-border-color: "#fff"
// avatar-group-overlapping: "-8px"
// avatar-group-space: "3px"
// avatar-size-base: "32px"
// avatar-size-lg: "40px"
// avatar-size-sm: "24px"
// back-top-bg: "rgba(0, 0, 0, 0.45)"
// back-top-color: "#fff"
// back-top-hover-bg: "rgba(0, 0, 0, 0.85)"
// background-color-base: "#f5f5f5"
// background-color-light: "#fafafa"
// badge-color: "#ff4d4f"
// badge-dot-size: "6px"
// badge-font-size: "12px"
// badge-font-size-sm: "12px"
// badge-font-weight: "normal"
// badge-height: "20px"
// badge-height-sm: "14px"
// badge-status-size: "6px"
// badge-text-color: "#fff"
// black: "#000"
// blue-1: "#e6f7ff"
// blue-2: "#bae7ff"
// blue-3: "#91d5ff"
// blue-4: "#69c0ff"
// blue-5: "#40a9ff"
// blue-6: "#1890ff"
// blue-7: "#096dd9"
// blue-8: "#0050b3"
// blue-9: "#003a8c"
// blue-10: "#002766"
// blue-base: "#1890ff"
// body-background: "#fff"
// border-color-base: "#d9d9d9"
// border-color-inverse: "#fff"
// border-color-split: "#f0f0f0"
// border-radius-base: "2px"
// border-radius-sm: "2px"
// border-style-base: "solid"
// border-width-base: "1px"
// box-shadow-base: "0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)"
// breadcrumb-base-color: "rgba(0, 0, 0, 0.45)"
// breadcrumb-font-size: "14px"
// breadcrumb-icon-font-size: "14px"
// breadcrumb-last-item-color: "rgba(0, 0, 0, 0.85)"
// breadcrumb-link-color: "rgba(0, 0, 0, 0.45)"
// breadcrumb-link-color-hover: "#40a9ff"
// breadcrumb-separator-color: "rgba(0, 0, 0, 0.45)"
// breadcrumb-separator-margin: "0 8px"
// btn-border-radius-base: "2px"
// btn-border-radius-sm: "2px"
// btn-border-style: "solid"
// btn-border-width: "1px"
// btn-circle-size: "32px"
// btn-circle-size-lg: "40px"
// btn-circle-size-sm: "24px"
// btn-danger-bg: "#ff4d4f"
// btn-danger-border: "#ff4d4f"
// btn-danger-color: "#fff"
// btn-default-bg: "#fff"
// btn-default-border: "#d9d9d9"
// btn-default-color: "rgba(0, 0, 0, 0.85)"
// btn-default-ghost-bg: "transparent"
// btn-default-ghost-border: "#fff"
// btn-default-ghost-color: "#fff"
// btn-disable-bg: "#f5f5f5"
// btn-disable-border: "#d9d9d9"
// btn-disable-color: "rgba(0, 0, 0, 0.25)"
// btn-font-size-lg: "16px"
// btn-font-size-sm: "14px"
// btn-font-weight: "400"
// btn-group-border: "#40a9ff"
// btn-height-base: "32px"
// btn-height-lg: "40px"
// btn-height-sm: "24px"
// btn-line-height: "1.5715"
// btn-link-hover-bg: "transparent"
// btn-padding-horizontal-base: "15px"
// btn-padding-horizontal-lg: "15px"
// btn-padding-horizontal-sm: "7px"
// btn-primary-bg: "#1890ff"
// btn-primary-color: "#fff"
// btn-primary-shadow: "0 2px 0 rgba(0, 0, 0, 0.045)"
// btn-shadow: "0 2px 0 rgba(0, 0, 0, 0.015)"
// btn-square-only-icon-size: "16px"
// btn-square-only-icon-size-lg: "18px"
// btn-square-only-icon-size-sm: "14px"
// btn-square-size: "32px"
// btn-square-size-lg: "40px"
// btn-square-size-sm: "24px"
// btn-text-hover-bg: "rgba(0, 0, 0, 0.018)"
// btn-text-shadow: "0 -1px 0 rgba(0, 0, 0, 0.12)"
// calendar-bg: "#fff"
// calendar-border-color: "#fff"
// calendar-full-bg: "#fff"
// calendar-full-panel-bg: "#fff"
// calendar-input-bg: "#fff"
// calendar-item-active-bg: "#e6f7ff"
// card-actions-background: "#fff"
// card-actions-li-margin: "12px 0"
// card-background: "#fff"
// card-head-background: "transparent"
// card-head-color: "rgba(0, 0, 0, 0.85)"
// card-head-extra-color: "rgba(0, 0, 0, 0.85)"
// card-head-font-size: "16px"
// card-head-font-size-sm: "14px"
// card-head-height: "48px"
// card-head-height-sm: "36px"
// card-head-padding: "16px"
// card-head-padding-sm: "8px"
// card-head-tabs-margin-bottom: "-17px"
// card-inner-head-padding: "12px"
// card-padding-base: "24px"
// card-padding-base-sm: "12px"
// card-radius: "2px"
// card-shadow: "0 1px 2px -2px rgba(0, 0, 0, 0.16), 0 3px 6px 0 rgba(0, 0, 0, 0.12), 0 5px 12px 4px rgba(0, 0, 0, 0.09)"
// card-skeleton-bg: "#cfd8dc"
// carousel-dot-active-width: "24px"
// carousel-dot-height: "3px"
// carousel-dot-width: "16px"
// cascader-bg: "#fff"
// cascader-dropdown-edge-child-vertical-padding: "4px"
// cascader-dropdown-font-size: "14px"
// cascader-dropdown-line-height: "22px"
// cascader-dropdown-vertical-padding: "5px"
// cascader-item-selected-bg: "#e6f7ff"
// cascader-menu-bg: "#fff"
// cascader-menu-border-color-split: "#f0f0f0"
// checkbox-border-width: "1px"
// checkbox-check-bg: "#fff"
// checkbox-check-color: "#fff"
// checkbox-color: "#1890ff"
// checkbox-group-item-margin-right: "8px"
// checkbox-size: "16px"
// code-family: "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace"
// collapse-content-bg: "#fff"
// collapse-content-padding: "16px"
// collapse-header-arrow-left: "16px"
// collapse-header-bg: "#fafafa"
// collapse-header-padding: "12px 16px"
// collapse-header-padding-extra: "40px"
// collapse-panel-border-radius: "2px"
// comment-action-color: "rgba(0, 0, 0, 0.45)"
// comment-action-hover-color: "#595959"
// comment-actions-margin-bottom: "inherit"
// comment-actions-margin-top: "12px"
// comment-author-name-color: "rgba(0, 0, 0, 0.45)"
// comment-author-time-color: "#ccc"
// comment-bg: "inherit"
// comment-content-detail-p-margin-bottom: "inherit"
// comment-font-size-base: "14px"
// comment-font-size-sm: "12px"
// comment-nest-indent: "44px"
// comment-padding-base: "16px 0"
// component-background: "#fff"
// control-padding-horizontal: "12px"
// control-padding-horizontal-sm: "8px"
// cyan-1: "#e6fffb"
// cyan-2: "#b5f5ec"
// cyan-3: "#87e8de"
// cyan-4: "#5cdbd3"
// cyan-5: "#36cfc9"
// cyan-6: "#13c2c2"
// cyan-7: "#08979c"
// cyan-8: "#006d75"
// cyan-9: "#00474f"
// cyan-10: "#002329"
// cyan-base: "#13c2c2"
// descriptions-bg: "#fafafa"
// descriptions-default-padding: "16px 24px"
// descriptions-extra-color: "rgba(0, 0, 0, 0.85)"
// descriptions-item-label-colon-margin-left: "2px"
// descriptions-item-label-colon-margin-right: "8px"
// descriptions-item-padding-bottom: "16px"
// descriptions-item-trailing-colon: "true"
// descriptions-middle-padding: "12px 24px"
// descriptions-small-padding: "8px 16px"
// descriptions-title-margin-bottom: "20px"
// disabled-bg: "#f5f5f5"
// disabled-color: "rgba(0, 0, 0, 0.25)"
// disabled-color-dark: "rgba(255, 255, 255, 0.35)"
// divider-color: "rgba(0, 0, 0, 0.06)"
// divider-orientation-margin: "5%"
// divider-text-padding: "1em"
// drawer-bg: "#fff"
// drawer-body-padding: "24px"
// drawer-footer-padding-horizontal: "16px"
// drawer-footer-padding-vertical: "10px"
// drawer-header-close-size: "56px"
// drawer-header-padding: "16px 24px"
// dropdown-edge-child-vertical-padding: "4px"
// dropdown-font-size: "14px"
// dropdown-line-height: "22px"
// dropdown-menu-bg: "#fff"
// dropdown-menu-submenu-disabled-bg: "#fff"
// dropdown-selected-color: "#1890ff"
// dropdown-vertical-padding: "5px"
// ease-base-in: "cubic-bezier(0.9, 0, 0.3, 0.7)"
// ease-base-out: "cubic-bezier(0.7, 0.3, 0.1, 1)"
// ease-in: "cubic-bezier(0.55, 0.055, 0.675, 0.19)"
// ease-in-back: "cubic-bezier(0.71, -0.46, 0.88, 0.6)"
// ease-in-circ: "cubic-bezier(0.6, 0.04, 0.98, 0.34)"
// ease-in-out: "cubic-bezier(0.645, 0.045, 0.355, 1)"
// ease-in-out-back: "cubic-bezier(0.71, -0.46, 0.29, 1.46)"
// ease-in-out-circ: "cubic-bezier(0.78, 0.14, 0.15, 0.86)"
// ease-in-out-quint: "cubic-bezier(0.86, 0, 0.07, 1)"
// ease-in-quint: "cubic-bezier(0.755, 0.05, 0.855, 0.06)"
// ease-out: "cubic-bezier(0.215, 0.61, 0.355, 1)"
// ease-out-back: "cubic-bezier(0.12, 0.4, 0.29, 1.46)"
// ease-out-circ: "cubic-bezier(0.08, 0.82, 0.17, 1)"
// ease-out-quint: "cubic-bezier(0.23, 1, 0.32, 1)"
// empty-font-size: "14px"
// error-color: "#ff4d4f"
// font-family: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
// font-feature-settings-base: "'tnum'"
// font-size-base: "14px"
// font-size-lg: "16px"
// font-size-sm: "12px"
// font-variant-base: "tabular-nums"
// form-error-input-bg: "#fff"
// form-item-label-colon-margin-left: "2px"
// form-item-label-colon-margin-right: "8px"
// form-item-label-font-size: "14px"
// form-item-label-height: "32px"
// form-item-margin-bottom: "24px"
// form-item-trailing-colon: "true"
// form-vertical-label-margin: "0"
// form-vertical-label-padding: "0 0 8px"
// form-warning-input-bg: "#fff"
// geekblue-1: "#f0f5ff"
// geekblue-2: "#d6e4ff"
// geekblue-3: "#adc6ff"
// geekblue-4: "#85a5ff"
// geekblue-5: "#597ef7"
// geekblue-6: "#2f54eb"
// geekblue-7: "#1d39c4"
// geekblue-8: "#10239e"
// geekblue-9: "#061178"
// geekblue-10: "#030852"
// geekblue-base: "#2f54eb"
// gold-1: "#fffbe6"
// gold-2: "#fff1b8"
// gold-3: "#ffe58f"
// gold-4: "#ffd666"
// gold-5: "#ffc53d"
// gold-6: "#faad14"
// gold-7: "#d48806"
// gold-8: "#ad6800"
// gold-9: "#874d00"
// gold-10: "#613400"
// gold-base: "#faad14"
// green-1: "#f6ffed"
// green-2: "#d9f7be"
// green-3: "#b7eb8f"
// green-4: "#95de64"
// green-5: "#73d13d"
// green-6: "#52c41a"
// green-7: "#389e0d"
// green-8: "#237804"
// green-9: "#135200"
// green-10: "#092b00"
// green-base: "#52c41a"
// grid-columns: "24"
// heading-1-size: "38px"
// heading-2-size: "30px"
// heading-3-size: "24px"
// heading-4-size: "20px"
// heading-5-size: "16px"
// heading-color: "rgba(0, 0, 0, 0.85)"
// height-base: "32px"
// height-lg: "40px"
// height-sm: "24px"
// highlight-color: "#ff4d4f"
// html-selector: "html"
// icon-color: "inherit"
// icon-color-hover: "rgba(0, 0, 0, 0.75)"
// iconfont-css-prefix: "anticon"
// image-bg: "#f5f5f5"
// image-color: "#fff"
// image-font-size-base: "24px"
// image-mask-font-size: "16px"
// image-preview-operation-color: "rgba(255, 255, 255, 0.85)"
// image-preview-operation-disabled-color: "rgba(255, 255, 255, 0.25)"
// image-preview-operation-size: "18px"
// image-size-base: "48px"
// info-color: "#1890ff"
// input-addon-bg: "#fafafa"
// input-bg: "#fff"
// input-border-color: "#d9d9d9"
// input-color: "rgba(0, 0, 0, 0.85)"
// input-disabled-bg: "#f5f5f5"
// input-disabled-color: "rgba(0, 0, 0, 0.25)"
// input-height-base: "32px"
// input-height-lg: "40px"
// input-height-sm: "24px"
// input-hover-border-color: "#40a9ff"
// input-icon-color: "rgba(0, 0, 0, 0.85)"
// input-icon-hover-color: "rgba(0, 0, 0, 0.85)"
// input-number-handler-active-bg: "#f4f4f4"
// input-number-handler-bg: "#fff"
// input-number-handler-border-color: "#d9d9d9"
// input-number-handler-hover-bg: "#40a9ff"
// input-number-hover-border-color: "#40a9ff"
// input-outline-offset: "0 0"
// input-padding-horizontal: "11px"
// input-padding-horizontal-base: "11px"
// input-padding-horizontal-lg: "11px"
// input-padding-horizontal-sm: "7px"
// input-padding-vertical-base: "4px"
// input-padding-vertical-lg: "6.5px"
// input-padding-vertical-sm: "0px"
// input-placeholder-color: "#bfbfbf"
// item-active-bg: "#e6f7ff"
// item-hover-bg: "#f5f5f5"
// label-color: "rgba(0, 0, 0, 0.85)"
// label-required-color: "#ff4d4f"
// layout-body-background: "#f0f2f5"
// layout-footer-background: "#f0f2f5"
// layout-footer-padding: "24px 50px"
// layout-header-background: "#001529"
// layout-header-color: "rgba(0, 0, 0, 0.85)"
// layout-header-height: "64px"
// layout-header-padding: "0 50px"
// layout-sider-background: "#001529"
// layout-sider-background-light: "#fff"
// layout-trigger-background: "#002140"
// layout-trigger-background-light: "#fff"
// layout-trigger-color: "#fff"
// layout-trigger-color-light: "rgba(0, 0, 0, 0.85)"
// layout-trigger-height: "48px"
// layout-zero-trigger-height: "42px"
// layout-zero-trigger-width: "36px"
// lime-1: "#fcffe6"
// lime-2: "#f4ffb8"
// lime-3: "#eaff8f"
// lime-4: "#d3f261"
// lime-5: "#bae637"
// lime-6: "#a0d911"
// lime-7: "#7cb305"
// lime-8: "#5b8c00"
// lime-9: "#3f6600"
// lime-10: "#254000"
// lime-base: "#a0d911"
// line-height-base: "1.5715"
// link-active-color: "#096dd9"
// link-color: "#1890ff"
// link-decoration: "none"
// link-focus-decoration: "none"
// link-focus-outline: "0"
// link-hover-color: "#40a9ff"
// link-hover-decoration: "none"
// list-customize-card-bg: "#fff"
// list-empty-text-padding: "16px"
// list-footer-background: "transparent"
// list-header-background: "transparent"
// list-item-meta-avatar-margin-right: "16px"
// list-item-meta-description-font-size: "14px"
// list-item-meta-margin-bottom: "16px"
// list-item-meta-title-margin-bottom: "12px"
// list-item-padding: "12px 0"
// list-item-padding-lg: "16px 24px"
// list-item-padding-sm: "8px 16px"
// magenta-1: "#fff0f6"
// magenta-2: "#ffd6e7"
// magenta-3: "#ffadd2"
// magenta-4: "#ff85c0"
// magenta-5: "#f759ab"
// magenta-6: "#eb2f96"
// magenta-7: "#c41d7f"
// magenta-8: "#9e1068"
// magenta-9: "#780650"
// magenta-10: "#520339"
// magenta-base: "#eb2f96"
// margin-lg: "24px"
// margin-md: "16px"
// margin-sm: "12px"
// margin-xs: "8px"
// margin-xss: "4px"
// mentions-dropdown-bg: "#fff"
// mentions-dropdown-menu-item-hover-bg: "#fff"
// menu-bg: "#fff"
// menu-collapsed-width: "80px"
// menu-dark-arrow-color: "#fff"
// menu-dark-bg: "#001529"
// menu-dark-color: "rgba(255, 255, 255, 0.65)"
// menu-dark-danger-color: "#ff4d4f"
// menu-dark-highlight-color: "#fff"
// menu-dark-inline-submenu-bg: "#000c17"
// menu-dark-item-active-bg: "#1890ff"
// menu-dark-item-active-danger-bg: "#ff4d4f"
// menu-dark-item-hover-bg: "transparent"
// menu-dark-selected-item-icon-color: "#fff"
// menu-dark-selected-item-text-color: "#fff"
// menu-highlight-color: "#1890ff"
// menu-highlight-danger-color: "#ff4d4f"
// menu-horizontal-line-height: "46px"
// menu-icon-margin-right: "10px"
// menu-icon-size: "14px"
// menu-icon-size-lg: "16px"
// menu-inline-submenu-bg: "#fafafa"
// menu-inline-toplevel-item-height: "40px"
// menu-item-active-bg: "#e6f7ff"
// menu-item-active-border-width: "3px"
// menu-item-active-danger-bg: "#fff1f0"
// menu-item-boundary-margin: "8px"
// menu-item-color: "rgba(0, 0, 0, 0.85)"
// menu-item-font-size: "14px"
// menu-item-group-height: "1.5715"
// menu-item-group-title-color: "rgba(0, 0, 0, 0.45)"
// menu-item-group-title-font-size: "14px"
// menu-item-height: "40px"
// menu-item-padding: "0 20px"
// menu-item-vertical-margin: "4px"
// menu-popup-bg: "#fff"
// message-notice-content-bg: "#fff"
// message-notice-content-padding: "10px 16px"
// modal-body-padding: "24px"
// modal-close-color: "rgba(0, 0, 0, 0.45)"
// modal-confirm-body-padding: "32px 32px 24px"
// modal-content-bg: "#fff"
// modal-footer-bg: "transparent"
// modal-footer-border-color-split: "#f0f0f0"
// modal-footer-border-style: "solid"
// modal-footer-border-width: "1px"
// modal-footer-padding-horizontal: "16px"
// modal-footer-padding-vertical: "10px"
// modal-header-bg: "#fff"
// modal-header-border-color-split: "#f0f0f0"
// modal-header-border-style: "solid"
// modal-header-border-width: "1px"
// modal-header-close-size: "56px"
// modal-header-padding: "16px 24px"
// modal-header-padding-horizontal: "24px"
// modal-header-padding-vertical: "16px"
// modal-header-title-font-size: "16px"
// modal-header-title-line-height: "22px"
// modal-heading-color: "rgba(0, 0, 0, 0.85)"
// modal-mask-bg: "rgba(0, 0, 0, 0.45)"
// normal-color: "#d9d9d9"
// notification-bg: "#fff"
// notification-padding-horizontal: "24px"
// notification-padding-vertical: "16px"
// orange-1: "#fff7e6"
// orange-2: "#ffe7ba"
// orange-3: "#ffd591"
// orange-4: "#ffc069"
// orange-5: "#ffa940"
// orange-6: "#fa8c16"
// orange-7: "#d46b08"
// orange-8: "#ad4e00"
// orange-9: "#873800"
// orange-10: "#612500"
// orange-base: "#fa8c16"
// outline-blur-size: "0"
// outline-color: "#1890ff"
// outline-fade: "20%"
// outline-width: "2px"
// padding-lg: "24px"
// padding-md: "16px"
// padding-sm: "12px"
// padding-xs: "8px"
// padding-xss: "4px"
// page-header-back-color: "#000"
// page-header-content-padding-vertical: "12px"
// page-header-ghost-bg: "inherit"
// page-header-heading-sub-title: "14px"
// page-header-heading-title: "20px"
// page-header-padding: "24px"
// page-header-padding-breadcrumb: "12px"
// page-header-padding-vertical: "16px"
// page-header-tabs-tab-font-size: "16px"
// pagination-font-family: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
// pagination-font-weight-active: "500"
// pagination-item-bg: "#fff"
// pagination-item-bg-active: "#fff"
// pagination-item-disabled-bg-active: "#dbdbdb"
// pagination-item-disabled-color-active: "#fff"
// pagination-item-input-bg: "#fff"
// pagination-item-link-bg: "#fff"
// pagination-item-size: "32px"
// pagination-item-size-sm: "24px"
// pagination-mini-options-size-changer-top: "0px"
// picker-basic-cell-active-with-range-color: "#e6f7ff"
// picker-basic-cell-disabled-bg: "#f5f5f5"
// picker-basic-cell-hover-color: "#f5f5f5"
// picker-basic-cell-hover-with-range-color: "#cbe6ff"
// picker-bg: "#fff"
// picker-border-color: "#f0f0f0"
// picker-date-hover-range-border-color: "#7ec1ff"
// picker-date-hover-range-color: "#cbe6ff"
// picker-panel-cell-height: "24px"
// picker-panel-cell-width: "36px"
// picker-panel-without-time-cell-height: "66px"
// picker-text-height: "40px"
// picker-time-panel-cell-height: "28px"
// picker-time-panel-column-height: "224px"
// picker-time-panel-column-width: "56px"
// pink-1: "#fff0f6"
// pink-2: "#ffd6e7"
// pink-3: "#ffadd2"
// pink-4: "#ff85c0"
// pink-5: "#f759ab"
// pink-6: "#eb2f96"
// pink-7: "#c41d7f"
// pink-8: "#9e1068"
// pink-9: "#780650"
// pink-10: "#520339"
// pink-base: "#eb2f96"
// popover-arrow-color: "#fff"
// popover-arrow-outer-color: "#fff"
// popover-arrow-width: "6px"
// popover-background: "#fff"
// popover-bg: "#fff"
// popover-color: "rgba(0, 0, 0, 0.85)"
// popover-customize-border-color: "#f0f0f0"
// popover-distance: "10px"
// popover-min-height: "32px"
// popover-min-width: "177px"
// popover-padding-horizontal: "16px"
// preset-colors: "pink, magenta, red, volcano, orange, yellow, gold, cyan, lime, green, blue, geekblue, purple"
// primary-1: "#e6f7ff"
// primary-2: "#bae7ff"
// primary-3: "#91d5ff"
// primary-4: "#69c0ff"
// primary-5: "#40a9ff"
// primary-6: "#1890ff"
// primary-7: "#096dd9"
// primary-8: "#0050b3"
// primary-9: "#003a8c"
// primary-10: "#002766"
// primary-color: "#1890ff"
// process-tail-color: "#f0f0f0"
// processing-color: "#1890ff"
// progress-circle-text-font-size: "1em"
// progress-default-color: "#1890ff"
// progress-info-text-color: "rgba(0, 0, 0, 0.85)"
// progress-radius: "100px"
// progress-remaining-color: "#f5f5f5"
// progress-steps-item-bg: "#f3f3f3"
// progress-text-color: "rgba(0, 0, 0, 0.85)"
// progress-text-font-size: "1em"
// purple-1: "#f9f0ff"
// purple-2: "#efdbff"
// purple-3: "#d3adf7"
// purple-4: "#b37feb"
// purple-5: "#9254de"
// purple-6: "#722ed1"
// purple-7: "#531dab"
// purple-8: "#391085"
// purple-9: "#22075e"
// purple-10: "#120338"
// purple-base: "#722ed1"
// radio-border-width: "1px"
// radio-button-active-color: "#096dd9"
// radio-button-bg: "#fff"
// radio-button-checked-bg: "#fff"
// radio-button-color: "rgba(0, 0, 0, 0.85)"
// radio-button-hover-color: "#40a9ff"
// radio-disabled-button-checked-bg: "#e6e6e6"
// radio-disabled-button-checked-color: "rgba(0, 0, 0, 0.25)"
// radio-dot-color: "#1890ff"
// radio-dot-disabled-color: "rgba(0, 0, 0, 0.2)"
// radio-dot-size: "8px"
// radio-size: "16px"
// radio-solid-checked-color: "#fff"
// radio-top: "0.2em"
// radio-wrapper-margin-right: "8px"
// rate-star-bg: "#f0f0f0"
// rate-star-color: "#fadb14"
// rate-star-hover-scale: "scale(1.1)"
// rate-star-size: "20px"
// red-1: "#fff1f0"
// red-2: "#ffccc7"
// red-3: "#ffa39e"
// red-4: "#ff7875"
// red-5: "#ff4d4f"
// red-6: "#f5222d"
// red-7: "#cf1322"
// red-8: "#a8071a"
// red-9: "#820014"
// red-10: "#5c0011"
// red-base: "#f5222d"
// result-extra-margin: "24px 0 0 0"
// result-icon-font-size: "72px"
// result-subtitle-font-size: "14px"
// result-title-font-size: "24px"
// screen-lg: "992px"
// screen-lg-max: "1199px"
// screen-lg-min: "992px"
// screen-md: "768px"
// screen-md-max: "991px"
// screen-md-min: "768px"
// screen-sm: "576px"
// screen-sm-max: "767px"
// screen-sm-min: "576px"
// screen-xl: "1200px"
// screen-xl-max: "1599px"
// screen-xl-min: "1200px"
// screen-xs: "480px"
// screen-xs-max: "575px"
// screen-xs-min: "480px"
// screen-xxl: "1600px"
// screen-xxl-min: "1600px"
// select-background: "#fff"
// select-border-color: "#d9d9d9"
// select-clear-background: "#fff"
// select-dropdown-bg: "#fff"
// select-dropdown-font-size: "14px"
// select-dropdown-height: "32px"
// select-dropdown-line-height: "22px"
// select-dropdown-vertical-padding: "5px"
// select-item-active-bg: "#f5f5f5"
// select-item-selected-bg: "#e6f7ff"
// select-item-selected-color: "rgba(0, 0, 0, 0.85)"
// select-item-selected-font-weight: "600"
// select-multiple-disabled-background: "#f5f5f5"
// select-multiple-item-disabled-border-color: "#d9d9d9"
// select-multiple-item-disabled-color: "#bfbfbf"
// select-multiple-item-height: "24px"
// select-multiple-item-height-lg: "32px"
// select-multiple-item-spacing-half: "2px"
// select-selection-item-bg: "#f5f5f5"
// select-selection-item-border-color: "#f0f0f0"
// select-single-item-height-lg: "40px"
// shadow-1-down: "0 6px 16px -8px rgba(0, 0, 0, 0.08), 0 9px 28px 0 rgba(0, 0, 0, 0.05), 0 12px 48px 16px rgba(0, 0, 0, 0.03)"
// shadow-1-left: "-6px 0 16px -8px rgba(0, 0, 0, 0.08), -9px 0 28px 0 rgba(0, 0, 0, 0.05), -12px 0 48px 16px rgba(0, 0, 0, 0.03)"
// shadow-1-right: "6px 0 16px -8px rgba(0, 0, 0, 0.08), 9px 0 28px 0 rgba(0, 0, 0, 0.05), 12px 0 48px 16px rgba(0, 0, 0, 0.03)"
// shadow-1-up: "0 -6px 16px -8px rgba(0, 0, 0, 0.08), 0 -9px 28px 0 rgba(0, 0, 0, 0.05), 0 -12px 48px 16px rgba(0, 0, 0, 0.03)"
// shadow-2: "0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)"
// shadow-color: "rgba(0, 0, 0, 0.15)"
// shadow-color-inverse: "#fff"
// skeleton-color: "rgba(190, 190, 190, 0.2)"
// skeleton-paragraph-li-height: "16px"
// skeleton-paragraph-li-margin-top: "16px"
// skeleton-paragraph-margin-top: "28px"
// skeleton-title-height: "16px"
// skeleton-title-paragraph-margin-top: "24px"
// skeleton-to-color: "rgba(129, 129, 129, 0.24)"
// slider-disabled-background-color: "#fff"
// slider-disabled-color: "rgba(0, 0, 0, 0.25)"
// slider-dot-border-color: "#f0f0f0"
// slider-dot-border-color-active: "#8cc8ff"
// slider-handle-background-color: "#fff"
// slider-handle-border-width: "2px"
// slider-handle-color: "#91d5ff"
// slider-handle-color-focus: "#46a6ff"
// slider-handle-color-focus-shadow: "rgba(24, 144, 255, 0.12)"
// slider-handle-color-hover: "#69c0ff"
// slider-handle-color-tooltip-open: "#1890ff"
// slider-handle-margin-top: "-5px"
// slider-handle-shadow: "0"
// slider-handle-size: "14px"
// slider-margin: "10px 6px 10px"
// slider-rail-background-color: "#f5f5f5"
// slider-rail-background-color-hover: "#e1e1e1"
// slider-track-background-color: "#91d5ff"
// slider-track-background-color-hover: "#69c0ff"
// spin-dot-size: "20px"
// spin-dot-size-lg: "32px"
// spin-dot-size-sm: "14px"
// statistic-content-font-size: "24px"
// statistic-font-family: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
// statistic-title-font-size: "14px"
// statistic-unit-font-size: "24px"
// steps-background: "#fff"
// steps-current-dot-size: "10px"
// steps-description-max-width: "140px"
// steps-dot-size: "8px"
// steps-dot-top: "2px"
// steps-icon-custom-font-size: "24px"
// steps-icon-custom-size: "32px"
// steps-icon-custom-top: "0px"
// steps-icon-font-size: "16px"
// steps-icon-margin: "0 8px 0 0"
// steps-icon-size: "32px"
// steps-icon-top: "-0.5px"
// steps-nav-arrow-color: "rgba(0, 0, 0, 0.25)"
// steps-nav-content-max-width: "auto"
// steps-small-icon-margin: "0 8px 0 0"
// steps-small-icon-size: "24px"
// steps-title-line-height: "32px"
// steps-vertical-icon-width: "16px"
// steps-vertical-tail-width: "16px"
// steps-vertical-tail-width-sm: "12px"
// success-color: "#52c41a"
// switch-bg: "#fff"
// switch-color: "#1890ff"
// switch-disabled-opacity: "0.4"
// switch-height: "22px"
// switch-inner-margin-max: "25px"
// switch-inner-margin-min: "7px"
// switch-min-width: "44px"
// switch-padding: "2px"
// switch-shadow-color: "rgba(0, 35, 11, 0.2)"
// switch-sm-height: "16px"
// switch-sm-inner-margin-max: "18px"
// switch-sm-inner-margin-min: "5px"
// switch-sm-min-width: "28px"
// table-bg: "#fff"
// table-body-selected-sort-bg: "#e6f7ff"
// table-body-sort-bg: "#fafafa"
// table-border-color: "#f0f0f0"
// table-border-radius-base: "2px"
// table-expand-icon-bg: "#fff"
// table-expanded-row-bg: "#fbfbfb"
// table-filter-btns-bg: "inherit"
// table-filter-dropdown-bg: "#fff"
// table-font-size: "14px"
// table-font-size-md: "14px"
// table-font-size-sm: "14px"
// table-footer-bg: "#fafafa"
// table-footer-color: "rgba(0, 0, 0, 0.85)"
// table-header-bg: "#fafafa"
// table-header-bg-sm: "#fafafa"
// table-header-color: "rgba(0, 0, 0, 0.85)"
// table-header-filter-active-bg: "#e5e5e5"
// table-header-sort-active-bg: "#f2f2f2"
// table-header-sort-bg: "#f5f5f5"
// table-padding-horizontal: "16px"
// table-padding-horizontal-md: "8px"
// table-padding-horizontal-sm: "8px"
// table-padding-vertical: "16px"
// table-padding-vertical-md: "12px"
// table-padding-vertical-sm: "8px"
// table-row-hover-bg: "#fafafa"
// table-selected-row-bg: "#e6f7ff"
// table-selected-row-color: "inherit"
// table-selected-row-hover-bg: "#dcf4ff"
// table-selection-column-width: "32px"
// table-sticky-scroll-bar-bg: "rgba(0, 0, 0, 0.35)"
// table-sticky-scroll-bar-radius: "4px"
// tabs-active-color: "#096dd9"
// tabs-bar-margin: "0 0 16px 0"
// tabs-card-active-color: "#1890ff"
// tabs-card-gutter: "2px"
// tabs-card-head-background: "#fafafa"
// tabs-card-height: "40px"
// tabs-card-horizontal-padding: "8px 16px"
// tabs-card-horizontal-padding-lg: "7px 16px 6px"
// tabs-card-horizontal-padding-sm: "6px 16px"
// tabs-card-tab-active-border-top: "2px solid transparent"
// tabs-highlight-color: "#1890ff"
// tabs-horizontal-gutter: "32px"
// tabs-horizontal-margin: "0 0 0 32px"
// tabs-horizontal-margin-rtl: "0 0 0 32px"
// tabs-horizontal-padding: "12px 0"
// tabs-horizontal-padding-lg: "16px 0"
// tabs-horizontal-padding-sm: "8px 0"
// tabs-hover-color: "#40a9ff"
// tabs-ink-bar-color: "#1890ff"
// tabs-scrolling-size: "32px"
// tabs-title-font-size: "14px"
// tabs-title-font-size-lg: "16px"
// tabs-title-font-size-sm: "14px"
// tabs-vertical-margin: "16px 0 0 0"
// tabs-vertical-padding: "8px 24px"
// tag-default-bg: "#fafafa"
// tag-default-color: "rgba(0, 0, 0, 0.85)"
// tag-font-size: "12px"
// tag-line-height: "20px"
// text-color: "rgba(0, 0, 0, 0.85)"
// text-color-dark: "rgba(255, 255, 255, 0.85)"
// text-color-inverse: "#fff"
// text-color-secondary: "rgba(0, 0, 0, 0.45)"
// text-color-secondary-dark: "rgba(255, 255, 255, 0.65)"
// text-selection-bg: "#1890ff"
// theme: "default"
// timeline-color: "#f0f0f0"
// timeline-dot-bg: "#fff"
// timeline-dot-border-width: "2px"
// timeline-dot-color: "#1890ff"
// timeline-item-padding-bottom: "20px"
// timeline-width: "2px"
// tooltip-arrow-color: "rgba(0, 0, 0, 0.75)"
// tooltip-arrow-width: "5px"
// tooltip-bg: "rgba(0, 0, 0, 0.75)"
// tooltip-color: "#fff"
// tooltip-distance: "8px"
// tooltip-max-width: "250px"
// transfer-disabled-bg: "#f5f5f5"
// transfer-header-height: "40px"
// transfer-item-height: "32px"
// transfer-item-hover-bg: "#f5f5f5"
// transfer-item-padding-vertical: "6px"
// transfer-list-height: "200px"
// transfer-list-search-icon-top: "12px"
// tree-bg: "#fff"
// tree-child-padding: "18px"
// tree-directory-selected-bg: "#1890ff"
// tree-directory-selected-color: "#fff"
// tree-node-hover-bg: "#f5f5f5"
// tree-node-selected-bg: "#bae7ff"
// tree-title-height: "24px"
// typography-title-font-weight: "600"
// typography-title-margin-bottom: "0.5em"
// typography-title-margin-top: "1.2em"
// upload-actions-color: "rgba(0, 0, 0, 0.45)"
// volcano-1: "#fff2e8"
// volcano-2: "#ffd8bf"
// volcano-3: "#ffbb96"
// volcano-4: "#ff9c6e"
// volcano-5: "#ff7a45"
// volcano-6: "#fa541c"
// volcano-7: "#d4380d"
// volcano-8: "#ad2102"
// volcano-9: "#871400"
// volcano-10: "#610b00"
// volcano-base: "#fa541c"
// warning-color: "#faad14"
// wave-animation-width: "6px"
// white: "#fff"
// yellow-1: "#feffe6"
// yellow-2: "#ffffb8"
// yellow-3: "#fffb8f"
// yellow-4: "#fff566"
// yellow-5: "#ffec3d"
// yellow-6: "#fadb14"
// yellow-7: "#d4b106"
// yellow-8: "#ad8b00"
// yellow-9: "#876800"
// yellow-10: "#614700"
// yellow-base: "#fadb14"
// zindex-affix: "10"
// zindex-back-top: "10"
// zindex-badge: "auto"
// zindex-dropdown: "1050"
// zindex-image: "1080"
// zindex-message: "1010"
// zindex-modal: "1000"
// zindex-modal-mask: "1000"
// zindex-notification: "1010"
// zindex-picker: "1050"
// zindex-picker-panel: "10"
// zindex-popoconfirm: "1060"
// zindex-popover: "1030"
// zindex-popup-close: "10"
// zindex-table-fixed: "2"
// zindex-tooltip: "1070"
